apiVersion: v1
kind: Secret
metadata:
    name: s3-store-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: {{ .Values.longhorn.s3.accessKeyId | b64enc }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.longhorn.s3.accessKey | b64enc }}
    AWS_ENDPOINTS: {{ .Values.longhorn.s3.endpoint | b64enc }}