---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: rook-ceph-http
  namespace: rook-ceph
spec:
  parentRefs:
  - kind: Gateway
    name: my-gateway
    namespace: default
    sectionName: shared-tls
  hostnames:
  - "ceph.apps.timgiertz.com"
  rules:
  - backendRefs:
    - name: rook-ceph-mgr-dashboard
      port: 8443
---