apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # https://docs.cilium.io/en/latest/configuration/argocd-issues/
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
  kustomize.buildOptions: "--enable-alpha-plugins --enable-exec --enable-helm"
---