namespace: argocd

resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref\=stable
  - projects/apps.yaml
  - bootstrap-app-set.yaml
  - argocd-initial-admin-secret.yaml

patches:
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-cm.yaml
  - path: argo-cd-repo-server-ksops-patch.yaml