apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
  api-token: {{ .Values.clusterIssuer.secret.apiToken }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: {{ .Values.clusterIssuer.server }}
        email: {{ .Values.clusterIssuer.email }}
        privateKeySecretRef:
            name: cert-issuer-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: solver-api-token-secret
                        key: api-token