# Postgres user
apiVersion: v1
type: kubernetes.io/basic-authsic-authsic-auth
data:
    username: {{ .Values.postgres.secret.username | b64enc }}
    password: {{ .Values.postgres.secret.password | b64enc }}
kind: Secret
metadata:
    name: app-secret