# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:npFzwOa/uYkPj8cIQdNpIN2CKVXBpNEsO/pgVXtYsXh8ttQ0tFNPCQ==,iv:iL/V9UF/XkTRtXKWXe7eWe/R95HgyobZKMflQCXBnak=,tag:93Hlr/eBwfxIA0X3lYl+6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNlVPRVpzSUZNZDNCdmdv
            ZXhid3NhTzRVUC84VW9JUWpXWUYzS1V0TENRCnZBc2NqZ3cvbmk2d0lzRG9BT2pk
            WWdGRE8zWE1HekVwMlBiNVJkQWs3RDQKLS0tIFFLUzJMV2JqbVRMaEVvcnJ5eDRH
            aFc2NXZacUZnMTFLam53M214RVdWaW8KBv4cgFCKlUMcmKNzb7V0a+wC3oLfeacv
            zuuCTgoZLW+7Q3FS9zZU+rc+bTIFHh+ec/FNFljiyxhkBpDCr5F7jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T15:50:41Z"
    mac: ENC[AES256_GCM,data:kUNf2Es2kqTFHegC9UGfJz+CZ9zEddXUSjbwDrGAj9JSbUN7IcaDA3UgHdLAe6RSGrkqdgAyHLmmbQw8csf/1LiYcwUKRjNkiUtd130iDNSeSQHukoeXbqo2y5idI3Bcg+wwwN1kF4wiD6vyaTKBP1B9saXg/Nx2hrb8yYLfPKI=,iv:30lcHYLuL7EDYsPAni2vaXtlPg2vtlmrKo8EWo2qDFU=,tag:q4RUKj19MIzQLqsI5xk/Dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:q0BtKtPIn/5WwS1Kkn0CJUxVk3G2BWBKatVEN2U+n8WXI7ata7RRrjsPk9nLIw==,iv:xJCd+4b05L4cJGkbEFkYo7CSlhGAsQsLjjny4PaKay0=,tag:eIc2UhavFImihVopF+6ToA==,type:str]
        email: ENC[AES256_GCM,data:eiYCJuJQRvjsMLpuwmAgH72o1bg=,iv:pwedIeL0HLNZa5LP/fmxoD69aLs5cH2qeyUyclzJYGM=,tag:6fgtxPOh5yLbxWSWTqUR2g==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:oDoQhTDxfMdxPYn5NeT0,iv:SZqr5fEBQ9cSYADJDBOPNNHN7jZ8Q3WtAIDX6G6hSYU=,tag:GcK2S6B1o+Fww2B0tAfO0Q==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:DXXmg4tyoBuT/u0d9nV+/efVpfGO72o=,iv:+LU1SUvSPhDvcGZyAboBfEuNv5mNIHfsurAXr7rFHjM=,tag:SLoBSRdaYzq2/VQrmC5v6g==,type:str]
                        key: ENC[AES256_GCM,data:hluRC4FTFy2n,iv:+eYmZ7AGlPg9tsKLrESu3RTDXpkZ4UVcHS1VJhxhMlg=,tag:rMmBn/f1aRPmmBrWN6kLgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNlVPRVpzSUZNZDNCdmdv
            ZXhid3NhTzRVUC84VW9JUWpXWUYzS1V0TENRCnZBc2NqZ3cvbmk2d0lzRG9BT2pk
            WWdGRE8zWE1HekVwMlBiNVJkQWs3RDQKLS0tIFFLUzJMV2JqbVRMaEVvcnJ5eDRH
            aFc2NXZacUZnMTFLam53M214RVdWaW8KBv4cgFCKlUMcmKNzb7V0a+wC3oLfeacv
            zuuCTgoZLW+7Q3FS9zZU+rc+bTIFHh+ec/FNFljiyxhkBpDCr5F7jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T15:50:41Z"
    mac: ENC[AES256_GCM,data:kUNf2Es2kqTFHegC9UGfJz+CZ9zEddXUSjbwDrGAj9JSbUN7IcaDA3UgHdLAe6RSGrkqdgAyHLmmbQw8csf/1LiYcwUKRjNkiUtd130iDNSeSQHukoeXbqo2y5idI3Bcg+wwwN1kF4wiD6vyaTKBP1B9saXg/Nx2hrb8yYLfPKI=,iv:30lcHYLuL7EDYsPAni2vaXtlPg2vtlmrKo8EWo2qDFU=,tag:q4RUKj19MIzQLqsI5xk/Dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
