# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:XfcK2WwmfD2uVQnRGAE6D/+4xargJk3U2unn/MervDMDqH47s+FxBg==,iv:5+ILyHvgsfPSAIUTGFbe1NYswm5KthJB2lW/BchLXnQ=,tag:eLNNwK4VaUh3wo/ir2kZ/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bUdhSVFBTmx6OHJ1YnBj
            ekQrclhjZVovNWRxSmNrZ1Jpa2w2TndzT1VjClU2QzE5eitYN2txUURGZSs4cldC
            OEljM2dwQTZESkRqT0dET1ZrQklzUncKLS0tIGZ3Wm9aNXNLQ1h5d25XcDV3a1Zi
            V01ZVHk2c3RJT2c1Qm1WSTAwa0twN3MK8Uz4ycEkifVPFDRtBAb7uBW7f7/vf/Hq
            3oWNLn5cgYoopxwPMpMs6LyLohjoORxo/zAUSc0ljMjMlOh/rklECQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T03:43:57Z"
    mac: ENC[AES256_GCM,data:8CcjLfapmfIYFw8a0m3SrxIQ8ZH+5A0OPS0BlrV59UcESIq8iBuUCpu3dqcoNv92P/aaCpZK44avaFpFWf3xvpmbY7qQv2W0anM075VoBziig3/ocz5VI89/a6tlnRpmKRz0dY+6LvweE4i9xqEiCVc8LdDZ/3HsMyTaPCpaQv4=,iv:0MDBc8KyPcVodE/SqvkIxonZLHjNL4rvpYqUctesDcQ=,tag:3MXl1DiauScLHNoRejuPfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:PLjIT/nHGIdjqs4O6U/AEglDwj1MueX22T7XANwWYr3m9Jzd/aE5F5fG8hrXjA==,iv:vhcu8w/Vj6ZojjpYKnH2/D8HQuAUaO+esCNfYLGh8To=,tag:8LKytk3X5J/YrqwISNlbTw==,type:str]
        email: ENC[AES256_GCM,data:k97+CB3fwSP/84xLD7IMUuKro2Y=,iv:qGigqMXfmnb7r3GGd5BURxBc6cYso/LzX+xiMe4ItQg=,tag:hxK7yJvOO3Qqj86QxnlTgA==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:+AAadrbHoluB1I1Cnowh,iv:e1kyHfytGzNdFmN+2n6tlgdI2VV8VpMlZb6eLBs4G1c=,tag:U90rNPMWZ8YqvkGWXxggfw==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:BdN7b0r9xJdJ2+CbGiaqA/U/Wrjptm0=,iv:MSmc1XX7nJSDO1fzo5TYLAPV3/rxGStLNfw1K+FXYfs=,tag:Mu9VqqbGrejvsBQ2H5FJDw==,type:str]
                        key: ENC[AES256_GCM,data:Dnxb6wq3pEZB,iv:WDoHDBg78dtagmzgt5NvxCGOWJJhROIwvOruKnjrw5o=,tag:ogIo1nG7I9X4oiUJCcblOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bUdhSVFBTmx6OHJ1YnBj
            ekQrclhjZVovNWRxSmNrZ1Jpa2w2TndzT1VjClU2QzE5eitYN2txUURGZSs4cldC
            OEljM2dwQTZESkRqT0dET1ZrQklzUncKLS0tIGZ3Wm9aNXNLQ1h5d25XcDV3a1Zi
            V01ZVHk2c3RJT2c1Qm1WSTAwa0twN3MK8Uz4ycEkifVPFDRtBAb7uBW7f7/vf/Hq
            3oWNLn5cgYoopxwPMpMs6LyLohjoORxo/zAUSc0ljMjMlOh/rklECQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T03:43:57Z"
    mac: ENC[AES256_GCM,data:8CcjLfapmfIYFw8a0m3SrxIQ8ZH+5A0OPS0BlrV59UcESIq8iBuUCpu3dqcoNv92P/aaCpZK44avaFpFWf3xvpmbY7qQv2W0anM075VoBziig3/ocz5VI89/a6tlnRpmKRz0dY+6LvweE4i9xqEiCVc8LdDZ/3HsMyTaPCpaQv4=,iv:0MDBc8KyPcVodE/SqvkIxonZLHjNL4rvpYqUctesDcQ=,tag:3MXl1DiauScLHNoRejuPfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
