apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret-v2
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:/2fgWcTjGhx11V9Hoz/Vp6KpKYzKq4wsCA4pvRGsDggLSQl6DMmnTg==,iv:eLSmjyZ7uV+YnrV2lPKq57leErJU5eaxalWSpRaLRbc=,tag:tyhcLCf33JY7r1KWtuhyXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dkUwWWMyWk9zY1AyRWxZ
            RE82WG1hMFdjWEJXNGxWdjN6SHF3WmVkb2hjCjZjK0t1cVRDa2paWTloWFhlODg5
            YXZDY1I4U0ZycWlRZ1M5WFl1Z3FhTGsKLS0tIEJudzBwZTV5Zmt3d1NzMTMyYlo5
            ZHJXVDR0aG5mNTlzR1BPblBXdUhBZWMK34YOruiE8m2P83yqZrEQTyykOOD3zydy
            BbP/Jfs1HUjB+I29Xd32PYySMcFfLX3OUTFKvY3hLOpP+wMHCPzmFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-16T03:58:02Z"
    mac: ENC[AES256_GCM,data:McU6bQOU0PyHJv80jUvmgqpbcd9nhbl+qWbtMqhWV/AXupkfKPaXYs1UEHZCWclBusHBddzBZnDwwBIZhsTdcL7IyGVr+u/pDmqyTpFTmF1i4om5HPkxPsGyWhqR6M/dqC6MOt0FKyf3Sw25j1Rz7Zeb8OdrPoOrKffNttV9kIA=,iv:4LYRzqwdQRfWPw6LYhsYroJgRwNQ84WKi8xY649WQq0=,tag:7fZARv4EJdmJHGZJv95v8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.2
