apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:EGSAfnclhb1FvTQMlogSdwAOvNVYckxPhR4mCUIy6DdGKaVWVIP/fQ==,iv:VYciKBVwi1iyTF9riQ6wC1N9whKGtZhVIiYYRK/Em3o=,tag:9H5eB2YOwyMxdoT2M3BgSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcUkwUVEzVzhRdVJid2ZK
            Wk90Z2pmaDdxZTNuN3lVTkRYMFh3WlpXYTE0CnFoQkNDajQzbUZYbmU3WGZXamRL
            Q2RpSWxRblo0UzhOaCsyclF3YllMYjgKLS0tIEVBa3c5dzY5R1lTL1I3b1hMb0Rz
            V2hhSWVlclM0M2RKZy92U3RBY1dRWkkKWlTqwwUYZ3TGx/Gk6DMiDpIc1hKr4/eZ
            O5vAjKpCkda9HouRVK2aL+kWuVeKxxC1IhlHxnLh0vEBBYDOXqDTtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T15:16:44Z"
    mac: ENC[AES256_GCM,data:hx4VjUZR8EYYFT3mg5zcFWQ4xdBIvYlMvMsxXOaoSNWQ3Q1q0xCaVQ7svDGlp6w+psG60cwS98+gaif2peOR2+dfYL42doqPUMPMXlT04a5ZGE4zk3/TT1vtDIOnDTHHeVJiMM38VVJN2BXf7xcf2bIqoQin5JQlkVB16K6c3mc=,iv:1gWyZhekvfuHBDe2sWiE4wCPscqFZs09d4t6eN3wtQs=,tag:i0Q0tP+ryrHeHurVIpY9Dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: timgiertz-prod-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:lXiQVME1rHDGTlSd5WRbiYQG8neXodkiN4eUplTYNEpC8BOKqiZqrb4PNWLoWg==,iv:qRGQ36kzfz1BThdPz0fUXW14sSs5gGKJvb4Ba1XvUQk=,tag:GHnvU9pquvRVNSo9mmi0+Q==,type:str]
        email: ENC[AES256_GCM,data:SIlPgrzyegZ0T3bu3TRXpjH5NKo=,iv:2heBOZItb++XMCmB1J1X+tTnuyLgj1Zn8aU7wvQ/kgY=,tag:G58lM/LyN1IOFxFP3cmznw==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:4/U+vYhIwIFF3rYkeboUoA==,iv:lUe2UKUliNXQlQGOdIdfFnQaQaTtIQITCaHke9jzt8A=,tag:gA8BAn6kz8Llx0TqaxIsAw==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:3SciXqWHpHsmi97Duz3cJ46h4IO79q4fGd/Z,iv:TTDFRuZSWTY97WoEap1uWH3qdUDA+00E08PS9wRF1AQ=,tag:myDI6l5cxgbSEvP5nKIEJg==,type:str]
                        key: ENC[AES256_GCM,data:SJ3uYUIPRsl3,iv:Chu4QNao+nwJ9wkTLwxvGAX4y10v4XLgn/hbenlpZQQ=,tag:z0zzZAxDBs2hEIIBaeO+vA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcUkwUVEzVzhRdVJid2ZK
            Wk90Z2pmaDdxZTNuN3lVTkRYMFh3WlpXYTE0CnFoQkNDajQzbUZYbmU3WGZXamRL
            Q2RpSWxRblo0UzhOaCsyclF3YllMYjgKLS0tIEVBa3c5dzY5R1lTL1I3b1hMb0Rz
            V2hhSWVlclM0M2RKZy92U3RBY1dRWkkKWlTqwwUYZ3TGx/Gk6DMiDpIc1hKr4/eZ
            O5vAjKpCkda9HouRVK2aL+kWuVeKxxC1IhlHxnLh0vEBBYDOXqDTtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T15:16:44Z"
    mac: ENC[AES256_GCM,data:hx4VjUZR8EYYFT3mg5zcFWQ4xdBIvYlMvMsxXOaoSNWQ3Q1q0xCaVQ7svDGlp6w+psG60cwS98+gaif2peOR2+dfYL42doqPUMPMXlT04a5ZGE4zk3/TT1vtDIOnDTHHeVJiMM38VVJN2BXf7xcf2bIqoQin5JQlkVB16K6c3mc=,iv:1gWyZhekvfuHBDe2sWiE4wCPscqFZs09d4t6eN3wtQs=,tag:i0Q0tP+ryrHeHurVIpY9Dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
