# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:HWaKKUdHdGsbTo6ab1tJQxtnxQ2hadN6XVDeSyuUvH03/LvTWabEoA==,iv:k0r1M84L2n5o0Wcz/HBBgrEZVTKz2gXDRC44ZoPQhS0=,tag:0VHYgHYSAy0V90ZhJS+C+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc0lnbk5hMi9BcXZvWkVR
            R1VGUVFBMEplUnozUkxuQTlQNnpyTXBOdVZrCkFGSzhuUU94N01LY0JISVFJWkQv
            aEtNU0t2U3JJd09teHRyOVlQQkNncUEKLS0tIHVjWk9ZM0VwSGhqSUJCM2RMVnpV
            VGxJbWRuejBjSVl1Y3FORWJYbVRhSE0K7K91+MDWUIOZ5Pz2TiPU937bSLlm4T/e
            RnaxzV9A/1kHryn6RdulpaPTxC0e7iWvA93Ia23fMDZO9jH6f+mVhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T16:25:27Z"
    mac: ENC[AES256_GCM,data:nvBX7l8/rNR5W3R+P6yNswKdIECu8Lp+5ssmLFMRvZqcPr+777JQf5l3XtgdiTBS4eVc5xA3xcvMUDj1SQJQSxveByMKj1cQ1OCbgBKsQ4IG7UArKpZ5YteT4cDSnKt1WBmrNiMMhF+GXrYeAhS9MLP/+mi7WUxBD6MgYeYxL/I=,iv:as62mbx/fp1xMGlh2nZiixdQixmSKA2bGOHVRfJkLNE=,tag:9Z1lbtAKEHqaCW95jATo6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:eeo6yym3pxjPcgst5pnHajWgZDdqSS4noapKgp1dz1c6/BhDab1IfeX8RIhNM4rVpDgjWo1F,iv:59jI3N81WzhrSqfxQczgiunVKQ7bGodwRBFITf3bFpY=,tag:vE+DGENK/nNH1wxGGUT1kA==,type:str]
        email: ENC[AES256_GCM,data:Ixkr0OFD2Ni1owhF2IUK02wWexI=,iv:fL8XAZEn3+bnvSLNLpKmgTMvgFzNjVaaRUMITYxEcjA=,tag:ImRxfN28U5stb1m1Ad96fw==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:G+kohAkXSCYkTp7cjV7c,iv:v5nWszPVjPlDA2ehzBRatZ9zjc2EhSnhEQfFx9i98Lw=,tag:wBdpSgr/ezdyjVDjKkY8Kw==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:ow9Q1tPk4Lc8WUTHAt1T3Hzpf0isVCc=,iv:uA6N20TavPRn0FOVBuL5YKFcmySH1LMaZaY2dDriuRw=,tag:3R6nAB3L2YNty5nBI5LNxA==,type:str]
                        key: ENC[AES256_GCM,data:gn73VJEabh8+,iv:/c3BAWpqr1Ib21jvZaouo9j9i1CTocEeDwt/gWEHy9o=,tag:Q2xqbspKJ1Z4jnT9Gd6YuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc0lnbk5hMi9BcXZvWkVR
            R1VGUVFBMEplUnozUkxuQTlQNnpyTXBOdVZrCkFGSzhuUU94N01LY0JISVFJWkQv
            aEtNU0t2U3JJd09teHRyOVlQQkNncUEKLS0tIHVjWk9ZM0VwSGhqSUJCM2RMVnpV
            VGxJbWRuejBjSVl1Y3FORWJYbVRhSE0K7K91+MDWUIOZ5Pz2TiPU937bSLlm4T/e
            RnaxzV9A/1kHryn6RdulpaPTxC0e7iWvA93Ia23fMDZO9jH6f+mVhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T16:25:27Z"
    mac: ENC[AES256_GCM,data:nvBX7l8/rNR5W3R+P6yNswKdIECu8Lp+5ssmLFMRvZqcPr+777JQf5l3XtgdiTBS4eVc5xA3xcvMUDj1SQJQSxveByMKj1cQ1OCbgBKsQ4IG7UArKpZ5YteT4cDSnKt1WBmrNiMMhF+GXrYeAhS9MLP/+mi7WUxBD6MgYeYxL/I=,iv:as62mbx/fp1xMGlh2nZiixdQixmSKA2bGOHVRfJkLNE=,tag:9Z1lbtAKEHqaCW95jATo6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
