apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:tGZZAhorxUvtciMIwn7sMyUaax8Qk4uK751QZusG1kR4KSagFSInyQ==,iv:Z9QDL6nsfi9HoVTsQHgtvsFNAbs2zdXoqdJ9yiNTFnc=,tag:I3YHfK4N6NEkZJNQhkeLGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZmdKbUJXSTMzbmxJK0VJ
            SGJDdnpXL1dzL2dram95bC9XMGpXQjRURXc0CjNJQjJjbEEzdll2Nm0rKy8rUDYr
            MWZMdW45czhmNDVTbDZubDF2M3NacHcKLS0tIEg0dTM0SlpzVGxZVyttVURrZkMz
            SVlCMm1LOUIySWFEZ3ppZ1dBMGRyWWMK8qD0XOP9nG+Ol7Akjr8eB91sx+EsUuaJ
            syzumzkKUwH/sEdPW6yqXNC/pauLcCxNy62p1+t98mi75E2XCeKJsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T20:01:05Z"
    mac: ENC[AES256_GCM,data:T4KTzyEcSUCxHF2B1gxlY0G8RkfRAgUidFFZJ8I68/5wbll6i5lhmaMlUwn0Gm23gAaFLXB3gy5VlhTUGTS2Qgt/IEDgklQV8J+EbgOBmMt3LN0S++4vcFzZhnxt6gOJmUpDQZ5N1nzJAGvLZjnNY46j7Km+9M8gmtSiVYATejk=,iv:EdR7Qy8uouV/4kHTKnnlO0YXp+UF+/Klzi+FK+RokmE=,tag:N5ZS8BefCdoCficxJ60VLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
