# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ve1O/MilzXgN16ZsmpRGxo+/TtmwNEyjQINHRh08OGrWVWfFYWFPhA==,iv:a8ZaMFITb7BbSd03I/5phrpZuVT+qjYWajfKamrgMjQ=,tag:1RTczELxDbDwLkE+iwOSbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV21nL3hSdjdDbkVrbUJa
            dW5sajJYQjlpcTF1aDRYRG9CTlBGa3AvRHdjCjdON3NIbUgza1Jmc1BqWFBuZ2ly
            WXpwRG4yY3lzaWI4SkYyczU2Qmdyem8KLS0tIFJKMGhHemVRVWhvTGdkbGxTNmZo
            Y3FVMkowSHpwZVM3bzlyNkV5bkhqd0kK6S0Hsb3p6R4VBsKu0XmCb2ePAZNmLxRW
            8oZirtxqkmdZg+GnwGsssLRouqkMv/EoXIqG2P3WGooxH7Dklr88lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T05:45:15Z"
    mac: ENC[AES256_GCM,data:uQFRp8JMccR5Iio+4ZuKkTLSlDPpoyvaHBSRQnRAlUIswgr3k+Nr4VBZco9UXkTwwbtksfF1n3kiVJjayJ1+aRzumTTV9IBputqd8mMnMMCKM3HCRuCG5M0rfPOwAia/diHPEm0W7OdBXwGHnIx/VZLoGznyuJBmh1UMlEBLSrA=,iv:R2+t8T8hGGE/DTYt21lXZAxUeQDASuLpLZsVGyevgDA=,tag:KnN9V/lNR+ltNQ0KiZ/eJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:fl3AyMraC203Dwq8KUDX2zkS5+/uwuVi8Y+Jlg4RAen7DkPtdhyZcYFISGH3xQ==,iv:dJ2/4BgbfiffZubuqw29/2JqNX8MvIEbz1Rr6br05Co=,tag:Fg92K1Z6ccfyJPXdXr0CRg==,type:str]
        email: ENC[AES256_GCM,data:zRDHcuht1dsJ1AOKWQMKBE9NpQA=,iv:oYfHrfbrTLFFZyjbX64fjf96Cy0IOIXO3ZGELMfQ1Hg=,tag:u7JLfA8ni1D8GsfOpz7mfQ==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:at++jLJkhFVaKF53o7E5,iv:IR5cgN0B8jSBqZOoQQISTKCUfkRrjV4SbQtiDtP7PxU=,tag:tZ8GMANNfbbs9eQJFz5IVA==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:83O3aZwq6hOMsvdFiAroya4jkziPmoM=,iv:JJGtR20cW6yN47X2sf5vb7qK0QabKA7ya8qslbjI1D0=,tag:jYphuThBoc/w8K+/8PRFOA==,type:str]
                        key: ENC[AES256_GCM,data:xAxBz8qpu3HT,iv:xAwQF7TQucuYwev5URH9ckkKSRhYFnX4b8WTJ1IBMfw=,tag:vQEAiXNZwPPbOStx0nUWHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV21nL3hSdjdDbkVrbUJa
            dW5sajJYQjlpcTF1aDRYRG9CTlBGa3AvRHdjCjdON3NIbUgza1Jmc1BqWFBuZ2ly
            WXpwRG4yY3lzaWI4SkYyczU2Qmdyem8KLS0tIFJKMGhHemVRVWhvTGdkbGxTNmZo
            Y3FVMkowSHpwZVM3bzlyNkV5bkhqd0kK6S0Hsb3p6R4VBsKu0XmCb2ePAZNmLxRW
            8oZirtxqkmdZg+GnwGsssLRouqkMv/EoXIqG2P3WGooxH7Dklr88lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T05:45:15Z"
    mac: ENC[AES256_GCM,data:uQFRp8JMccR5Iio+4ZuKkTLSlDPpoyvaHBSRQnRAlUIswgr3k+Nr4VBZco9UXkTwwbtksfF1n3kiVJjayJ1+aRzumTTV9IBputqd8mMnMMCKM3HCRuCG5M0rfPOwAia/diHPEm0W7OdBXwGHnIx/VZLoGznyuJBmh1UMlEBLSrA=,iv:R2+t8T8hGGE/DTYt21lXZAxUeQDASuLpLZsVGyevgDA=,tag:KnN9V/lNR+ltNQ0KiZ/eJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
