apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:85F/PJi4br7JvjnWqV3M1wQSOM9sLazBWuuyzjod3uO2ZhTX3BO7Aw==,iv:Yd6EfTQmHs2ZJTsyYxaN74MLYWq9bStrsqzJqk1irYs=,tag:FHX8a77YmxReB1gkK5VU/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcHFLNVYwSVMraDhwNGRB
            MWx6MlJYVVlnZFhMbUhWWkMwVkFkMERQdTNVCjF1bkZQOFV4b2xlbXVGekxNRWI1
            Uk4ra1hncFJJeStXcGhaVGtna0tQQ0kKLS0tIGROazdaaXZ1WWZ6WmZNYVBxMGxP
            Um0rN3ZHUE5qMk5KZEFFUmpodVRmbzQKaU6Gyq0UpZqKv22JoPF5Wlu8hGZM3T72
            kkP3ojtZnYY+fYXA5CY8H95Vw4HbnbSkXOuvzdkHo1BhK6CxxRgRFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T05:20:06Z"
    mac: ENC[AES256_GCM,data:Sq4lLNs088Z49LI7+Wo6vGOSYCDQ0oImHF4Q7WOjVmEmDSqfhC0gU304sAF7ruIpEgQtUPBz2YzW9FqMd9njeEy+62JqHgUEFVxfyqsQ/idhtkH3siPMe7mPDwguFDmodfzmuVH1OYrFNLONnMTZaaSAGV/zIjsHp1ZX2ROFOb0=,iv:9XPwTsADE21E1aw2n8DzA2gvZrQyBQIieKhy5vSVx+o=,tag:PJOixmi+40sDu/E6CnsnBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: timgiertz-prod-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:ecA4gayCxgha6rOjeG88azx73kPPxkUUa5Rei9oFP3d0wYafocRYwiULaL5Rpd8O5kFq2PT1,iv:exqivEOkNmofAW5zrVsY4P+Dxrm5S7xeZHR8y/11/xA=,tag:3s8Z0OauE2kU4Ga9bZc1bA==,type:str]
        #ENC[AES256_GCM,data:SLz4Z+kEvefOlzWDBoHtTWycA/1gR2A+5xuD8qwbsq3zXhaRKKz/cChmlJCvqGsAkkZuAIsYXg==,iv:R0O0oh6g9fWregdVOF+37EwP8IqEfCqHnLVmhgRpy20=,tag:XAosFfYkXAcsq4hQZ/jLZg==,type:comment]
        email: ENC[AES256_GCM,data:Y7JMKmLrT7pZGXj99ldvWGarRB8=,iv:Ppy6yR2TMVnS5VbPsbgH0j969bTWMehYRwkbDliDWSg=,tag:AOfKfMEUhz6Qit4yTtTSZQ==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:eFGj2ZrjLmqwIh98mNywIA==,iv:roJob4GEKtOP3hN58NrjH1o01EGmh4NHh4H62x0fMHY=,tag:C05PI3PBejJguy0vGrj3cw==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:SfURqqz4VLSPfMykKpZ2QrD5/pzVqgDfIlrR,iv:j3c0w0rc2fQewgi4ZByWQz9JMYgF9EWX2awxj7tWEDg=,tag:2cbwkJFy6pTEK61ld2VO7g==,type:str]
                        key: ENC[AES256_GCM,data:0sNrJG3wgAIu,iv:nozzUIiOpwI3d7A/zNaN6+2Pu3PZbpMfGrKbTJR1KpQ=,tag:GDqAR8UNFjZ/7zWVdadYwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcHFLNVYwSVMraDhwNGRB
            MWx6MlJYVVlnZFhMbUhWWkMwVkFkMERQdTNVCjF1bkZQOFV4b2xlbXVGekxNRWI1
            Uk4ra1hncFJJeStXcGhaVGtna0tQQ0kKLS0tIGROazdaaXZ1WWZ6WmZNYVBxMGxP
            Um0rN3ZHUE5qMk5KZEFFUmpodVRmbzQKaU6Gyq0UpZqKv22JoPF5Wlu8hGZM3T72
            kkP3ojtZnYY+fYXA5CY8H95Vw4HbnbSkXOuvzdkHo1BhK6CxxRgRFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T05:20:06Z"
    mac: ENC[AES256_GCM,data:Sq4lLNs088Z49LI7+Wo6vGOSYCDQ0oImHF4Q7WOjVmEmDSqfhC0gU304sAF7ruIpEgQtUPBz2YzW9FqMd9njeEy+62JqHgUEFVxfyqsQ/idhtkH3siPMe7mPDwguFDmodfzmuVH1OYrFNLONnMTZaaSAGV/zIjsHp1ZX2ROFOb0=,iv:9XPwTsADE21E1aw2n8DzA2gvZrQyBQIieKhy5vSVx+o=,tag:PJOixmi+40sDu/E6CnsnBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
