# Source: deployment/templates/apps/postgres/secret.enc.yaml
# Postgres user
apiVersion: v1
type: kubernetes.io/basic-authsic-authsic-auth
data:
    username: ENC[AES256_GCM,data:SJwpYA==,iv:C8hahbsVVxT2djlaX2n6UmjuPr1gZPpb5CALhkPCMiE=,tag:3h8fL/4uiodiHDlV/e1NDQ==,type:str]
    password: ENC[AES256_GCM,data:8da5OtGMg+flppVb,iv:t5U9nBpxil8dti12IHCY9dQlTzNGMy5qFM6P9F8kepI=,tag:yfwQXXbhnlH8l9KA7gPPLw==,type:str]
kind: Secret
metadata:
    name: app-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZGZsOWNFTFl5ZVF2WjBr
            cUJrRzc3QVFxR1J1aHNnRWU2NWlac21IMTI4ClZYN2NOZ0lYdllwa2RWWUd4TDFP
            ZTY3QVRRci9Sb0tVZWJSVlluUjVsVzAKLS0tIDk5dVkwRXZadXMrSTVVVDRLbG5H
            L05HWFBNbkEwSHd3WlM0UmpJbHh2LzgK7QFI7w1H08+thNtFpSstRRFlVKGKYIjU
            HHccIcH4/cuP/wA69AeFPmJ1nI+GV/Q3c1vwhN32/IeLDHEUMOcFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T05:45:15Z"
    mac: ENC[AES256_GCM,data:UmuP13Gug4cIsSuBvETOumDagFCxBjwQQaJzfLcY0HlpoBCAeFQv1Apl3Zlp4x417F/Bu80W9KySwa7MCJa1m8xHJkuGxNAMwCzKjJPfW3oyr6X9w9bHfMHCLyahba7pQuu3QFTZPa0gYZVuGJkajUW5zcaTNIERnbnRyFrTajc=,iv:DWic2b/eRGGhJ4+n9SeT3rHRCiP5VSJ+aYGq9tEPNXg=,tag:tRBNJHvDkjMMH4E/uz+ozw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
