# Postgres user
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:5bObeA==,iv:ijT57xtGFmtRYE1bJLLlEE+4pOTKdbblSR8rRZfTRrE=,tag:b65lDBFv41HotqYAbbhCDw==,type:str]
    password: ENC[AES256_GCM,data:H+zSZg+lgrdWEdYX,iv:umc5hBWFYe+9Q0+0RI/e3AgBu8kdFi+Oeg5X5RR3F/E=,tag:EkbUPAubmpunnxlUzOLO0A==,type:str]
kind: Secret
metadata:
    name: app-secret
type: kubernetes.io/basic-authsic-authsic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlY2JBZThJdndsV0lpZW5v
            NjUrQ0FkdW5MWGcwZWM3UFp6aUo0aUJyckI0Ci9lNXoxWmdqNHJYdjZnMkxtWWtt
            TWx4bXJVSy9GYjVpUGtleHBQOE93VDQKLS0tIFhGM3FEOVlYM0RNSzdtdHV2dTlx
            bkpuN3ZhSUNUUi96VE5tM1JUTURrZFkKKk6Mv8HuVYmlvETHo72+TxjCberjZKgl
            r+lAJQdOqXjTDvgCDcC8EQNGG/WTDruZXwAcsOh5/Nx9ZBqCAaPWUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T22:25:10Z"
    mac: ENC[AES256_GCM,data:WIPeewaimqbEeKnSYRmSSl2j92kOGO3yvFuZkix8LnxwS2fGn/4/vz3oDzZ6s3P2h6mTdZDAt2JfSyAWVen8osdzvd1tw2FjBin4+LsvWhf8uihP9pusSlz662R2mfs+rXAtD12Fsl+P17ajZEI2qCOh7EywMxC0GktZGV9BvvM=,iv:aofY8IcmSl04+fmWNc17Y8wNWR2T77NUCg2rwze9rSc=,tag:uQdGPGCiotAA3i8k5wiOnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
