# Source: deployment/templates/apps/postgres/secret.enc.yaml
# Postgres user
apiVersion: v1
type: kubernetes.io/basic-authsic-authsic-auth
data:
    username: ENC[AES256_GCM,data:OpuAyQ==,iv:xKSbvoD8wDNKTgfFvlEuvjPu9W7X/g+6ExVeFq1dbsM=,tag:hFYfERE3v3NJkWiK6rqGGQ==,type:str]
    password: ENC[AES256_GCM,data:yhcPIThkzQpOMD99,iv:IswR0dg9CaSdwWstewdY2giSYDLEaQQQYBLT29kFwFQ=,tag:xTQanxx6M9ir6p0VukjYaw==,type:str]
kind: Secret
metadata:
    name: app-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc2NCa1k0Ni9DSTJBb080
            S0dDLy9OT0NvbnJHWm4zejFQZlRQN3MxNWtVCi9sNXdrS3Q5UGoxNi9TNXNvNkxJ
            VjZ6MzVGMXN6OVJGNWd2ZWJzeTN6NHMKLS0tIFRhQWRnTUYxOVZjWk5FeXhpMjdM
            WSt3dnNwbitPOHFhSS91Q2JQZmJpUkUKwS6l8DCx936N/2jXfcvyfQUsGpYT2lwI
            fWNYcyyO4CjxCQgHRpc6sQ0FAGJN2yxJd13Uy0skYo+DoxJxsk9btA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T15:50:39Z"
    mac: ENC[AES256_GCM,data:5f5cyLxc2/6wuQLQ2pkOUpSTUeq9o/htm/aqcAAC/oiUYE5w/NkcmjQA5CQj5aGnkqYCPX0W8Sn2+lRaribbQic8I6spyUwgn4g1jlze4AWrZ0YZGCgVTRdfDeAALBRfHVZgD3qKnirVGq/2gurzSHaWkT8y8p+javybQFVEfvs=,iv:NBMYlZo+gQrw6D1gzUq22JtFJrzWQDwCAw+jQCtPVdY=,tag:Vn8I74fEf0scdnhD31cbXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
