# Source: deployment/templates/apps/postgres/secret.enc.yaml
# Postgres user
apiVersion: v1
type: kubernetes.io/basic-authsic-authsic-auth
data:
    username: ENC[AES256_GCM,data:M8nPAQ==,iv:4fZV5WNnYi8YCxmcLLmo1giZqy5PJncPnHGi+bHGlKA=,tag:tRIhB5OsUd/lRc5+KeMImw==,type:str]
    password: ENC[AES256_GCM,data:IRh5oJNBfuFyn9F1,iv:6Jj0hTnapCErFk1FdzsENl2GPCuCY/efNLe7YpgvOg0=,tag:9N9b31LxLBcYZh76p3Aozg==,type:str]
kind: Secret
metadata:
    name: app-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabTNYM0dzcm1nb1FEWW1I
            WG5EWUJoVFlOclNlakFaSEw4b0RpMFlnNGlnCmlUOVhPbHl1a3lLdzRwdzhDMVlh
            dFpuL2VNc2VLek12WllXU0lGZzVHL00KLS0tIDFtL09RVkQxNGMyaFF0TGVaRCtD
            MEVzTnZIVDJISTNneENtSTY2Q1hZamsKb/jFCC6r9N7hHRHWf5//nHYLAFO6cHs6
            FjoAXP6PO5S+tpfoVl3b4Pewx+19Ue+MPbOYEswymZjEL6BrA6Balg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T03:43:58Z"
    mac: ENC[AES256_GCM,data:I+fKB6c4zdrD11IZsDFPz/Li+4O5jAjFCWwMYA3mayZDvHIw7TK/0FFHtIHBUsbEYbEYg2K7sLjzOScKDg/SvFf7ajKw2ijqybyZ4NaOOXN7nqIKBPXx4PF/c9pBPyyMoOUTXp+VFzaKXDZGuEZxafDLqia/aw5+RrGyF3Fxxbw=,iv:JjicTQgykS01kel5mNT1nZmOpoazugF11q/rHm8LHGc=,tag:86cj0F5t2pUS3o1+i8QY/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
