# Source: deployment/templates/apps/postgres/secret.enc.yaml
# Postgres user
apiVersion: v1
type: kubernetes.io/basic-authsic-authsic-auth
data:
    username: ENC[AES256_GCM,data:DN4mBA==,iv:1ENJHNJUl0BeK36ePm9LD6tL7q3uLJSf0x5yTT8zt6E=,tag:w7TTd8k9JS5RpyjaT56nNA==,type:str]
    password: ENC[AES256_GCM,data:kLQ7wvVjyc0ccCxF,iv:FnzhZLttaUWxQbyuciwu9dnUcRfSNv2jkxISmaBZQBE=,tag:0XFa3VVr/8w4SqAb6o5Lcw==,type:str]
kind: Secret
metadata:
    name: app-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MCtQQTFReXpWbkVVMGdk
            ek8yMU1iMFpMT21MVmlOdkl2d3pmaTdoQ1NZCktTMjIvc1lzYjZWSE4wcmJiV2RI
            M25TeWNmTW0zaG9Cc0F3OXkvcGx0YnMKLS0tIDJqQXEwTytXSm9HZGN3UkJQd09H
            bkhrYW5JMlh1RE5Ia2lESTdEVWtkREkKTOsUMg9TcWeuXTth8t/+CEmdHvt0hefv
            bZ/xGu1QCZqAeDfyz+TpXh6yiv9lrb2n5IE9w7yp852kN8see4mUuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T16:25:28Z"
    mac: ENC[AES256_GCM,data:m+NfoCwFZVcdEyACh0Ix3tIrhljS7e+Em+0B7wH4oWqyZAsX5jzKcBms9zvx/IkYBhDpuGPlBOgBIScPImGMSwmYlsrjXwEeRcpjI+hi9pQl9QoA2ELcsBtcfksGo1JZ1R9KarlqAYCCNxJYGcAOn/R1bWOsk8XZr9/Dd7xYUnM=,iv:Vs4Zv+QwSOCspjKrFmgpVXwbNoNmfawaYtrv1jHWBw8=,tag:739ACFknLabK/P/YpumURg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
