subdomain: apps.example.com

clusterIssuer:
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  email: user@example.com
  secret:
    apiToken: --replace with token --

longhorn:
  s3:
    endpoint: https://s3.example.com:443
    accessKeyId: --replace with id --
    accessKey: --replace with key --

postgres:
  secret:
    username: --replace with username --
    password: --replace with password --

argocd:
  bootstrap:
    repoURL: https://github.com/--replace--/omni-kube-homelab.git
    repoPath: "deployment/*/*"
    branch: main