apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-timgiertz-com-tls
spec:
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  issuerRef:
    name: timgiertz-prod-issuer
    kind: ClusterIssuer
  commonName: "*.apps.timgiertz.com"
  dnsNames:
    - "*.apps.timgiertz.com"
  secretName: apps-timgiertz-com-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  annotations:
    cert-manager.io/cluster-issuer: timgiertz-prod-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - name: web-gw
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      hostname: "*.apps.timgiertz.com"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: apps-timgiertz-com-tls
---