apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: my-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    app: nginx
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: my-nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-timgiertz-com-tls
spec:
  secretName: wildcard-apps-timgiertz-com-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  issuerRef:
    name: timgiertz-prod-issuer
    kind: ClusterIssuer
  commonName: "*.apps.timgiertz.com"
  dnsNames:
    - "*.apps.timgiertz.com"
  secretName: apps-timgiertz-com-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  annotations:
    cert-manager.io/cluster-issuer: timgiertz-prod-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      hostname: test.apps.timgiertz.com
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: wildcard-apps-timgiertz-com-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-app-1
spec:
  parentRefs:
  - name: my-gateway
  hostnames:
  - test.apps.timgiertz.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: my-nginx-service
      port: 80
---