apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  ports:
    - name: http
      port: 9080
  selector:
    app: my-nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-nginx-account
  labels:
    account: my-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      serviceAccountName: my-nginx-account
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000