apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: --replace with token--
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: user@example.com
        privateKeySecretRef:
            name: cert-issuer-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: solver-api-token-secret
                        key: api-token