apiVersion: v1
kind: Secret
metadata:
    name: s3-store-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: --accessKeyId--
    AWS_SECRET_ACCESS_KEY: LS1hY2Nlc3NLZXktLQ==
    AWS_ENDPOINTS: https://s3.example.com