apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-identifier-daemonset
  namespace: node-identifier
spec:
  selector:
    matchLabels:
      app: node-identifier-app
  template:
    metadata:
      labels:
        app: node-identifier-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["/bin/sh", "-c"]
        args:
          - "echo \"{ \\\"nodeName\\\": \\\"${NODE_NAME}\\\", \\\"podName\\\": \\\"${POD_NAME}\\\" }\" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"