# Source: deployment/templates/apps/longhorn/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: s3-store-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6PToRepjrIYykyGugUEJ4nowGf+r8s7MfcfeqA==,iv:fXoNAFLrhGEFA2quBg45nT+ziSvwrVX8+Nj6x2Ckbuc=,tag:J3EqsHFVQStrwXgK9ULbHw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:s/Mr2pBUW/jOd6zChcsQay+on+/+uq53ptAWaA==,iv:ixVBMKaoLQ1Uu+/VGi0eEg5hSAQnKoOGQihg8oiFmgw=,tag:7ENGGbQeuJzqBEi1RQ/TJA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Edc3onWB3jRBSH75sGfZgpNBzERmWulHNC0G5tSi4mCT4V/L,iv:6ZpCggD0pzcwhYORJwA2Mnc+Fl5W4UlippY3KXi1ZuA=,tag:etk9Ossn8mhvBJz5F8jnKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOXR5eUZhVGZGc0NjK1J6
            QXU4OFhaTHVLM1BzbGs5azlSdkEraEVtcUMwCkxyVXdGM1ZXUGxFa2RnT2xiMmhr
            NXM2bmdGNGh2a1ZsMjhuMmdmZi9kVTgKLS0tIEtCSEZPM3c2YmNqS01mZktJbERD
            R0FmcDVqUjZRbGY2VFlhYUN4ZW9lNGsKR3EMSS5MODmO9dq6paPXPHXNZF4lu8JB
            Yj5OkEIheaO3g2Y5fG7ZQjSWQM7+seps0wijKaHYc5ouqVq41424Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T22:07:13Z"
    mac: ENC[AES256_GCM,data:FQpP4YsExnqGIzX9h2r7tk7p/XTyyFT80Yjibnv+Xdx2oSksdtq9juk5l9rQplBm/Kk+wQbW3rCKwgKJEdKBSiusvp1cA/N1Npl5o502F+R5gmr6X18p/6bY9fGvj+0/NcPmyjvtbOxGkRqSjIKSawLNMOcmpgMA2UiZdfnsK6o=,iv:uA10LqzCMvzKhyRsRPjrwG0Hvv+BDxWvWfWDH39veY8=,tag:aq3uIvMho6uyeWkgd6puag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
