apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      bgp.cilium.io/enabled: "true"
  bgpInstances:
  - localASN: 65015
    name: instance-65015
    peers:
    - name: peer-65014
      peerASN: 65014
      peerAddress: 192.168.100.1
      peerConfigRef:
        name: cilium-peer
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  families:
  - advertisements:
      matchLabels:
        advertise: bgp
    afi: ipv4
    safi: unicast
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 30
  timers:
    connectRetryTimeSeconds: 12
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  labels:
    advertise: bgp
  name: cilium-advert
spec:
  nodeSelector:
    matchLabels:
      bgp.cilium.io/enabled: "true"
  advertisements:
  - advertisementType: PodCIDR
  - advertisementType: Service
    selector:
      matchExpressions:
      - key: somekey
        operator: NotIn
        values:
        - never-used-value
    service:
      addresses:
      - LoadBalancerIP
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-lb-pool-01
spec:
  blocks:
  - cidr: 192.168.100.128/25