
# Postgres
apiVersion: v1
data:
    username: ENC[AES256_GCM,data:jmny8g==,iv:uO+h1GlMVRUi7xrX4WDlUcPzWfKNlnUQO+T4kbZ0M7g=,tag:ondGRndKNGnf9xADf3voww==,type:str]
    password: ENC[AES256_GCM,data:+rkMi034TSurC/bp,iv:q4qQakfAkWFGmKiF5YxBsRar1LPEjI2lrbExsKkyhYs=,tag:howsKfiRgLlooortayLrMw==,type:str]
kind: Secret
metadata:
    name: app-secret
    namespace: postgres-dev
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMFdEWS9SOFI5WTR5SjR4
            dWZWeEllWUtmK2dIaGFwdlZEcFBCeW9qTlQwCkhKZUtnVksySllmQktWa3RuY2wr
            WnhwZkJjQUVidXdqSHQ4QTk1R00vNW8KLS0tIDNzZ0hpdjVJZTRLNjUrV1NxTjRm
            eDdaalRSZmwzUHlPWHFJb1Ava25VSlkK6Ua5C3kMs4woxZg2okgZRbtZF5giHRgc
            T6ulFPyEDC+JBJ5O/wXVrLO0gkbBr7KH+uDorFHHp2e4ITo8At1huA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T00:46:33Z"
    mac: ENC[AES256_GCM,data:rmb6hPnos8hYxVWXWWS6q/AVx9BTfZmoGN8sSk4hPd4fHcFvEsSaG8ZrGbGNpQdQwQ6Bsw/d+N3L2ib8+/amgXVgQ3J3blJK/Dmj5P6xemeybWxTwA1lg5u+nf+oWlWGedQm9zox6VXr4QY5b2iL31TuzObl+f86GYhET0se3X4=,iv:VmRltfUBmYboT6vxeiFD/0Qr6DgKd8BjIH/m8yXdX1U=,tag:BkyAcbLuuEEN2+amsE+ERQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.2
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMFdEWS9SOFI5WTR5SjR4
            dWZWeEllWUtmK2dIaGFwdlZEcFBCeW9qTlQwCkhKZUtnVksySllmQktWa3RuY2wr
            WnhwZkJjQUVidXdqSHQ4QTk1R00vNW8KLS0tIDNzZ0hpdjVJZTRLNjUrV1NxTjRm
            eDdaalRSZmwzUHlPWHFJb1Ava25VSlkK6Ua5C3kMs4woxZg2okgZRbtZF5giHRgc
            T6ulFPyEDC+JBJ5O/wXVrLO0gkbBr7KH+uDorFHHp2e4ITo8At1huA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T00:46:33Z"
    mac: ENC[AES256_GCM,data:rmb6hPnos8hYxVWXWWS6q/AVx9BTfZmoGN8sSk4hPd4fHcFvEsSaG8ZrGbGNpQdQwQ6Bsw/d+N3L2ib8+/amgXVgQ3J3blJK/Dmj5P6xemeybWxTwA1lg5u+nf+oWlWGedQm9zox6VXr4QY5b2iL31TuzObl+f86GYhET0se3X4=,iv:VmRltfUBmYboT6vxeiFD/0Qr6DgKd8BjIH/m8yXdX1U=,tag:BkyAcbLuuEEN2+amsE+ERQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.2
---