
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.7.2
data:
  default-setting.yaml: |-
    priority-class: longhorn-critical
    disable-revision-counter: true
    default-data-path: /var/mnt/longhorn/
    default-replica-count: 2
    default-data-locality: best-effort
