apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVp1a3pKSGZWSFgwaG1uRFZ6R0s=
  AWS_SECRET_ACCESS_KEY: bU1GOU1BTjJuNFlZRUFtOURjeFhscnZoOEZwYlRvb2F2S25KcnQ3MA==
  AWS_ENDPOINTS: aHR0cHM6Ly9zMy50aW1naWVydHouY29tOjQ0Mw==