apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: YXBw
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: postgres-system-tcp
spec:
  parentRefs:
  - kind: Gateway
    name: shared-default-gateway
    namespace: default
    sectionName: shared-tcp
  rules:
    backendRefs:
    - name: cluster-example-initdb-rw
      port: 5432
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-initdb
spec:
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret
  instances: 3
  storage:
    size: 2Gi
    storageClass: longhorn-postgres-storage
  superuserSecret:
    name: superuser-secret
  walStorage:
    size: 2Gi
    storageClass: longhorn-postgres-storage
