namespace: argocd

resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref\=stable
  - bootstrap-app-set.yaml

patches:
  - path: config.yaml
  - path: params.yaml
  #- path: deployment.yaml
  #- path: service.yaml