apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:RpQKJEsh+1vuEVOxo5tUB9WPhz/AAg==,iv:d09GzN6vduOm8TOwrbZxtBvgxB/o392/L1IsMgEABFw=,tag:uMF35mEN6QfimiDcFv+iWA==,type:str]
# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN08zSTlFTDVzUUdyajRM
            d0VLYnkvQmd0REViTDdEcHRPM0NiWEcrZ3h3CnYxNHR1UFo3Wlc5S1ZDKzZ0aUZm
            akhpNUZGd0N4a1pUamlDd1hCclh2b3MKLS0tIGExWUdQRWtvUFk4ZDBQOENKSUNN
            bjhHWllKOEN5M3lqOHVBTzRuZHBXSE0KtxQEjLEHHf0zQwH/ApYpnsw8FhLu0thQ
            ALtnCQoUtT5S+jnj0Z9lqwuXgl+Ku4LZkMvDZDI7bwrMhSzzOhH2uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T05:27:51Z"
    mac: ENC[AES256_GCM,data:ZtnexoHLlxFHLePHCEABi3oDOJqZjeEM9jxu82mBpV8nF3CzGWkDB+bqEs8k1vEOUODAW+FdQgaMoWF/sfO8MtsKj4oMsl7oQU/eeRqchWMu83KFwM/1Kcww5QNBC77U2hbwgWH5yroCU5x2gWRPWeKynL5FCqmSlLqCxQ2Ds84=,iv:YZQtHkejOeh/cDNKdyT+cw3Sztu3xUxj6VDmPaPw4Ig=,tag:rbf9EUTWXlCmFlrNgyWBbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:0QW4ktKOpvJDUf8UHiKSjonXUfnbr3McVXEbMtyAY0Ixb5X6RBCjvhh9vFCoTi0FfG4l5TBT,iv:ZlaPYicoAsOGRge6seWVXF7NZQ9adYluGDVkt8GAQKA=,tag:umkZMpKxeA3Cmdy/16+ljg==,type:str]
        email: ENC[AES256_GCM,data:M2suay+2VFxdWkoQYLQ7HA==,iv:i6p53fQ1nmaPqzWapHNBCWnn0j9diSdDCqVKncLxY98=,tag:8zkNvp5Iy+M2dRLZMqHWnA==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:EMw8fK/xpRm3fZmvqB9b,iv:zp3xm2p9pqLl71JkcgxoSwnGdPZnJv9B9EEHnEvG76c=,tag:XYoP2C2EU3nroTPktrFWnw==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:yfEvxGZgw4mZJxMdC/5ap6njvXYLL5k=,iv:O7V7oF0SLFMqz33UFMMlKKtJqMVM69lupVLTolJy97g=,tag:H75iK/GTEaB8Zfcq0pB9Kw==,type:str]
                        key: ENC[AES256_GCM,data:Et3+Ly5xHu3m,iv:KV4gYp4fQwihcAEZtWEr8j5ZqTxC/PdaPb8qCGFEVZA=,tag:egqAYPlXGXQSuTQTCd4o2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN08zSTlFTDVzUUdyajRM
            d0VLYnkvQmd0REViTDdEcHRPM0NiWEcrZ3h3CnYxNHR1UFo3Wlc5S1ZDKzZ0aUZm
            akhpNUZGd0N4a1pUamlDd1hCclh2b3MKLS0tIGExWUdQRWtvUFk4ZDBQOENKSUNN
            bjhHWllKOEN5M3lqOHVBTzRuZHBXSE0KtxQEjLEHHf0zQwH/ApYpnsw8FhLu0thQ
            ALtnCQoUtT5S+jnj0Z9lqwuXgl+Ku4LZkMvDZDI7bwrMhSzzOhH2uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T05:27:51Z"
    mac: ENC[AES256_GCM,data:ZtnexoHLlxFHLePHCEABi3oDOJqZjeEM9jxu82mBpV8nF3CzGWkDB+bqEs8k1vEOUODAW+FdQgaMoWF/sfO8MtsKj4oMsl7oQU/eeRqchWMu83KFwM/1Kcww5QNBC77U2hbwgWH5yroCU5x2gWRPWeKynL5FCqmSlLqCxQ2Ds84=,iv:YZQtHkejOeh/cDNKdyT+cw3Sztu3xUxj6VDmPaPw4Ig=,tag:rbf9EUTWXlCmFlrNgyWBbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
