# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:NYQfFB7nwvC5+jHpbrA7LeSOF3YeTuE=,iv:P3kH2sj9MiE3t6U2gL/BxFG6Dl+OMdiDiv0CkJyUh6w=,tag:C4VOhVRPKPTJhqM1cUg+Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNjlSN2xWalh2aXhrenJZ
            K2wyYmhEdzBQUG01by80ekZUbE1BQ1N4RFdNCkczdmpIamY5RTdXUHN2YlZPRlFu
            ZlJIcGFoVFJPUGsxOVVtU0gybGhFMEUKLS0tIDhCb21raGlqM0EvenF1LzQwMlo0
            UjdMT3NOcnkvY2t6MTZFaktHRGJZTWMKa0DwPDrzvp8hAqAcRyY7mr2DFZgrY5nD
            iRC252w3xblpWa6nlmEUzFTVQ5UXhrSv9/G56nv/wSjMV9VGvlnw3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T22:07:13Z"
    mac: ENC[AES256_GCM,data:XeeMcDldeDHzFNjBdRiqvPR/gmQIkD9XaytFNrsEFM11ugzFphQVm4nC7BLAhvuI5fZKXRmThIedMzDyy3UswdnguHoU2mLjGceAJ0MlvstZnxRmCskTMQq2mG5mJpA0aISTXME6kqYb2SanaXZUT1v+rTkEEbQjodXt64PlSRs=,iv:X8tLa2SsByD2Q3Zem1WEJC0mtJNgxYR0hCQdXQ3tFlw=,tag:8+cZ4zBWBcOeKFxyGKsoQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
# Source: deployment/templates/apps/cert-manager/secret.enc.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:llTjxBSGbU+cA4E0GyLmRCALLPz8a7kYYtVPFIZh+/9eOhjAq1m7w914DxoZtHOB2vLO2+zr,iv:THYVOBdnfGyicbcKBrkgTMuQJg42CxTxo8ycZBRnvec=,tag:2LyVrrQVEMuxhdB298DF7Q==,type:str]
        email: ENC[AES256_GCM,data:Nlt/cLsudZ6w7t2D7AD1+A==,iv:B/gfEu1pilFzN/b1VqVo3khFaxe2qkEV1TtY2HOvHrY=,tag:DfqPPr8mczIvvTQzvF0WGQ==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:FXTIqre3zXK9y9BkUnoG,iv:bZUAZlY9cb72rFy+E+yugnnEi2eaQvobG0W6y4ONpl8=,tag:lRP+HLJNqWvQx2EDwhBWlg==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:sigKL1O21Yrfvtc2D4eMxrOCUEpXNCY=,iv:dwCwEP9FXnDQBKeLWQ4iMMjmycEhmONAl4YvX41M9hA=,tag:CZQj+Dp6YgNRCQLh6dwAJA==,type:str]
                        key: ENC[AES256_GCM,data:7DGk/TOMMN0P,iv:i+HSrS8NG9l099gjlea9a82ChJciwmxv7haig8wAIDw=,tag:qglywXk+0vhjgGC59NgUFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNjlSN2xWalh2aXhrenJZ
            K2wyYmhEdzBQUG01by80ekZUbE1BQ1N4RFdNCkczdmpIamY5RTdXUHN2YlZPRlFu
            ZlJIcGFoVFJPUGsxOVVtU0gybGhFMEUKLS0tIDhCb21raGlqM0EvenF1LzQwMlo0
            UjdMT3NOcnkvY2t6MTZFaktHRGJZTWMKa0DwPDrzvp8hAqAcRyY7mr2DFZgrY5nD
            iRC252w3xblpWa6nlmEUzFTVQ5UXhrSv9/G56nv/wSjMV9VGvlnw3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T22:07:13Z"
    mac: ENC[AES256_GCM,data:XeeMcDldeDHzFNjBdRiqvPR/gmQIkD9XaytFNrsEFM11ugzFphQVm4nC7BLAhvuI5fZKXRmThIedMzDyy3UswdnguHoU2mLjGceAJ0MlvstZnxRmCskTMQq2mG5mJpA0aISTXME6kqYb2SanaXZUT1v+rTkEEbQjodXt64PlSRs=,iv:X8tLa2SsByD2Q3Zem1WEJC0mtJNgxYR0hCQdXQ3tFlw=,tag:8+cZ4zBWBcOeKFxyGKsoQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
