apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:8DutcNYDggT5Vv7PQZ9QM0fS3+SrKFEKsPkEs32lzDTLXR6q2vHStg==,iv:Y6hOo8bIoPo0nv4RAUgX676fsJQXV9srhmdcD5cFy8M=,tag:S+x6zfr14q+9yjZRfgb03A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTmlKam9yU0VzWHU2bW5C
            aWtDTVFLZ1lGamwrcDBBeFUwZ0xTaTc0aFZ3CjgwMENSVHE5QU14SWhNY3lab1pJ
            ZnFSMy8vMmVYZUlNbHltRTljU3BPMmMKLS0tIEllWHIvelloem1OQVJoTzhwR0lZ
            UnBPNWZMcEpiY1lGb2syeU5xaFBHZ1EKg5lxLVH1UzAVluPHGjF4A7Jnsy/4wSPx
            bI74LWtEW5q4Q+U5GkF9CKPk3niEoslCUnJzfZ3pC+hd7A3BURazIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-08T02:08:31Z"
    mac: ENC[AES256_GCM,data:KQbTdwjos3jEEXPqhjsXHcfY4PX2LhxgInPV6gG4Yytxx/zLjbVH1bXs6VC+8esxqvxHCXpaeBfjFKJp4m5dGStD1MWV4kQ3Byspjy/MAEQBRpZLvMdkRNmyIL7AaTCFaYpDB4E6tMt81PzWoMGzxXoYyz88xM0m31Fms/0XpuU=,iv:idkIE6SHED8tiA6jre+PkJ9CMZO4BFOEaL1hmR/8phA=,tag:ubKtgo9qOGItIjL0ZX2TUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:XHqJpP2uQg3cCCXcubhNKb5ZnIiqHw3qW6YovK4cwaVJN9kBooAoEUJcpG/RyIR8kaG1H89R,iv:Go803rRQmsp1FpYsgPl19t5spWrFiWZZPNjE4mH8hDU=,tag:w+Pa0bj5aron8PuLHtb7Nw==,type:str]
        email: ENC[AES256_GCM,data:QdGKgKfAWZIgb073AkaPbbIA5ug=,iv:/TrZ79T9AhY3YhNCGMmmtAC6UI+1s7Rj20OBWBIoFyI=,tag:V11FKbVvO1vtvA4z3lHfSw==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:wFpa9XtZu1q8Qihy3b9H,iv:JPNjB7JaCIiXC7Ykae1yhWKpBSmwtCQHXXpxa3aGLQo=,tag:uA+0mEGJHSSP5zHs8FLwbQ==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:TtLj3DQGIOet4nF1KsdG++1wTXXQi6Y=,iv:JtJ11A5paP4J/vkDpwp4KsER+7TVOIcww0On54hGp3I=,tag:Zu80m3zHYcw1a3GCHE8kbg==,type:str]
                        key: ENC[AES256_GCM,data:ZCbFiklWcJXQ,iv:GCDNqCA0ok3Y0Yb/Q4ftQ2/2GCVxNK5LFEragTsourk=,tag:UwiFvYOVSxDTFYaKzJZ07Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTmlKam9yU0VzWHU2bW5C
            aWtDTVFLZ1lGamwrcDBBeFUwZ0xTaTc0aFZ3CjgwMENSVHE5QU14SWhNY3lab1pJ
            ZnFSMy8vMmVYZUlNbHltRTljU3BPMmMKLS0tIEllWHIvelloem1OQVJoTzhwR0lZ
            UnBPNWZMcEpiY1lGb2syeU5xaFBHZ1EKg5lxLVH1UzAVluPHGjF4A7Jnsy/4wSPx
            bI74LWtEW5q4Q+U5GkF9CKPk3niEoslCUnJzfZ3pC+hd7A3BURazIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-08T02:08:31Z"
    mac: ENC[AES256_GCM,data:KQbTdwjos3jEEXPqhjsXHcfY4PX2LhxgInPV6gG4Yytxx/zLjbVH1bXs6VC+8esxqvxHCXpaeBfjFKJp4m5dGStD1MWV4kQ3Byspjy/MAEQBRpZLvMdkRNmyIL7AaTCFaYpDB4E6tMt81PzWoMGzxXoYyz88xM0m31Fms/0XpuU=,iv:idkIE6SHED8tiA6jre+PkJ9CMZO4BFOEaL1hmR/8phA=,tag:ubKtgo9qOGItIjL0ZX2TUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
