apiVersion: v1
kind: Secret
metadata:
    name: solver-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:pn3Dvf2GNtke3zHwy6mS74hVYemB6zdE3O4L0HmicuA73sREGL8POA==,iv:BPssgz/b0UgkGE/CvUYt0o8h8XY44C1hrYK67qh+0gE=,tag:obbB2dM2evzFDAKHuIMJqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXby92VHhEdVd2MndiajFo
            NkdnZnM5VWs1SFpNUHJCRnhCWncxQmN4TTNBClc0RUQ0YlZIS0ZhdGJyRkdQQVlV
            RVJMb3lBYWJKdlZkNndLY0ZyZnFsRjgKLS0tIEQ0RVJ6SWd5WDFMSDZpWHRVMmNi
            bWg5NC9RdDJpeWFCeHF3d1IvR1ZJVlEKvK6ixd7SXvnsH7VpUZ64qAyDVWH6Tkxw
            0S/aRtNXAGw/SN45o3r1uFDeyoyF2lHatVsOoEPd/Sgwn2HoVbL9kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T16:52:00Z"
    mac: ENC[AES256_GCM,data:RITuc2Csj7dkEoex+VP/RDNYCMR3iLcMy5HWw42M0t812F3ujtxxwMELumN0wiAosf1Bd3LrvTksI9brR+tmb3EeefSxA9Hf+Ai0A4NwN3HGtO1kyPsEpRLCFfOz3v7CR6A2NnMcJg7vouJX2CAEGOWsqWf+I9mJ+RvhkvAZV5g=,iv:vfPns4pOibTCscwZxQSIb3tO5LZKX/kH4j7cpdw0mbo=,tag:qNqNJ4YJBHY7UnTP3hZfuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: domain-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: ENC[AES256_GCM,data:2Ht+87ZVKDgjot+g2tiRKW1ATMoSYAK1+pDBd2IjdJAyc3weSTbE7TVz7tF2BEm807f+w1cy,iv:Z9Shlu87QRkvENxlaEQ+dz7W+GvEGKkRg6yXjXjYtoA=,tag:Oy2EyX9K+G1AJO36J/9DFw==,type:str]
        email: ENC[AES256_GCM,data:+SObwNs7MW6zKGaOyzYy6ueMeQI=,iv:AP2zB9ClhGTq941YxAwC8zMDMBxzXjC5w4CneEj2r7s=,tag:EPcLKOrMvR88nj07IvIqwQ==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:ySYxqr4ZgktOLeFlw5E+,iv:iQ7B3o01rAyTiQ9SWnFnvlA4MUUwYiPvd9BhzF0IjG0=,tag:ywp996Y1w8rU+1ehWi1ItA==,type:str]
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: ENC[AES256_GCM,data:Z7bS9VF1+lYiX1ufOH+FEbZ+iSYDX3M=,iv:D0dTRfdaTNM8WqhO7oncwpA3XXHM0kcIOkdQLEvhRRI=,tag:ZdIwhXi6y0W0ZdgWi+CCew==,type:str]
                        key: ENC[AES256_GCM,data:iYqKlFvZJxW7,iv:a9pPfAQ9poOVX8d6ZxLAdI7r2Rk0HmTc2M7Y8KyT5g8=,tag:suTgTrOQmMgQzqmS0Ls9RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXby92VHhEdVd2MndiajFo
            NkdnZnM5VWs1SFpNUHJCRnhCWncxQmN4TTNBClc0RUQ0YlZIS0ZhdGJyRkdQQVlV
            RVJMb3lBYWJKdlZkNndLY0ZyZnFsRjgKLS0tIEQ0RVJ6SWd5WDFMSDZpWHRVMmNi
            bWg5NC9RdDJpeWFCeHF3d1IvR1ZJVlEKvK6ixd7SXvnsH7VpUZ64qAyDVWH6Tkxw
            0S/aRtNXAGw/SN45o3r1uFDeyoyF2lHatVsOoEPd/Sgwn2HoVbL9kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T16:52:00Z"
    mac: ENC[AES256_GCM,data:RITuc2Csj7dkEoex+VP/RDNYCMR3iLcMy5HWw42M0t812F3ujtxxwMELumN0wiAosf1Bd3LrvTksI9brR+tmb3EeefSxA9Hf+Ai0A4NwN3HGtO1kyPsEpRLCFfOz3v7CR6A2NnMcJg7vouJX2CAEGOWsqWf+I9mJ+RvhkvAZV5g=,iv:vfPns4pOibTCscwZxQSIb3tO5LZKX/kH4j7cpdw0mbo=,tag:qNqNJ4YJBHY7UnTP3hZfuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
