# Source: deployment/templates/apps/longhorn/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: s3-store-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mSUTGpEfXrEqoGoHVCYRic176m/FtCgNjZzV6Q==,iv:YYYlurCnINcPMZ471UlFzRCTNJ2JQDSvfEKrZ/awHM0=,tag:K6bXvrHGGIRlJoWTTtkbng==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gQdH0H29pkeL0tUol94wBlKU+MXQr0koInaAS90w0TmQr16iSE/MADp79mwQ8SLrzL4CLcCg84k=,iv:X6ZSCdJzS4Dpa5h0NWXebc0D6qOCIgMMLdt6vga0DRU=,tag:eBAe+4WRuIJOynK/k2lxEg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:sKC4DwXaGJr0xLkkC8kEjJnEPIdRlXYjodGx69uRugbq4x7+xSXZwA==,iv:ce/2TX7a3AcCzY1J6EayCJnwDLFT/A2/ZaeWcno9pf0=,tag:hjUDij9x0vxlnBdvH7TopQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbWNGb1RMeUNWY3dDTjMv
            VmtsTmZjTXhEb3dheXdCdDYyYXlIcUw3WUVjCmRPMStCSWlic0sxZTdDTHRFb3JK
            OUJlTjVOK3ViSkJwQ1hsTnpNWXpHQ00KLS0tIGVkeHBIR29IdlU4SUp0a0txN0M3
            QkFTd3ZpKzUvdmwrdlVnSVQyMkZmUjAKqCLGpTYifpTTJioy08wKOOHHd+MXmOBm
            WjX6sSWCuX8V2AeMvZMXa0UZerZlKX6IcOqKMNUluTWQ13xbA7XRCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T03:43:58Z"
    mac: ENC[AES256_GCM,data:UUDDXm/wI+TXsDnco47WmOGpNjGZg9IJjQsB54wPire1N7mptlSbJSBJDTyzi0aCFjmBANhI36k+X6600xykHu1rVgsagdVyv6FZTXfsJ5o+aBiX7wOMKK+Bv0UaghDK/bXzYw6aU6bHdNvFrUZtx6nxpWTgL4rCMfr+ea6R4dc=,iv:jEqOtkP3PLzpoeJG3SglqogoK1RNyh7Gx9JMttgSX/U=,tag:tb/sC3ZoPNNwCL8o7rAacQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
