# Source: deployment/templates/apps/longhorn/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: s3-store-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+gPbOKbWKV+/HQ+O6THuM5Lce0QNBOncMi14Gw==,iv:sLxm+NQGwMugqnYNw5w6jY/WLVZK0gNtvoAPWi2BN+M=,tag:jqt6AcNrZcWG5vMuD8GXaQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YPxq1/gzZDeEf9I8hOQiOX7MSUKPaQUD6HHBklWOXQdi7bC5qoTItPB6zDzKwzyETBe34TTCv08=,iv:y0LksD4z4durgcgNFcb7DqODqAqmg17tdRWYz2aas6M=,tag:6O5iZGBlMtA+3SQRLPqm8w==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:CgDdbfWIUjsnD4K9b/6xgbUUyDyKpatzUJNDBZZFZbtNYYv7t9oxkw==,iv:aBAKuYuOim7ZPWYmSCtq1wmo32kXf7bw3SipMqFXbCI=,tag:8m2NYnm8dMNld9hsqFEZXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQk5nelBucGhYUzlZVlZJ
            aFZyQjhhS3JjWExXSVJFdHZIT0FpMU8reG5FCm9GbnFSYUNMVHp2VVFGczhXRHJM
            b1FaRzVRTm80SmFpMWtjWTh5WEErTDAKLS0tIFFEYWFWTHRabXpYdGUyOG15N3ha
            WE9MdUJIeVJSem1FWnpPRERWRkZ5bmcKq3GoxjyG5O+ueNdJTh5AkMqf0EcrdqTl
            YjcqenmQ0OwXXCaQtq1FuuuKn4DV1eUSD+1iG8sSDqVQuUHUY3C4Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T16:25:28Z"
    mac: ENC[AES256_GCM,data:TioxiJCBN9W9jtGNeO5K/4XJNCjmrzGhbQOYrj0PJakfnfN+yC0slJ5I32an4u0fsTvQXsWmjL36jb/vZ6CIuWRvhy1etmFqUH9O/GUEu9Qhqk2Wzp7aH5CaqVbVt7hGNTHfn7HtdSzr91AzHz9WNeZcjQ6fsJmltX9QPUVPUKk=,iv:7iM7ApZz0JZUJpnjpIf+0S9duke2ljVZH/k2J95f3yo=,tag:i2I//GM87bt/lfhOUPDq1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
