apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:h9i0Oi9j8oghOPDNmsVd5uBi07JdGjp9qNRGbw==,iv:Lm3kwmcrj34r13/ugSBU/2qL25EdtUDsLr4bYG2Yp3s=,tag:RN0j16qyBQ8CDurfy/rTIw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rzG5hagzTiEQ1g6J5TULYQwIDTgQnQEtr8ZKQGVB8rAj5ppGkFYGJThyB6IJp0PbjnXpiaIZINg=,iv:kVoMN1/EUtFOOfGdbciKsbyU+l7MKlvd9GGOm07y3s0=,tag:oWIJPHVo+E33gWDHCUN9fg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:n92oltqZ4sKORI6a4ZypHfpcj5cLJzQvKu/6faroPO41/RfgFjF4vw==,iv:ZMrGRDUjPz9jTg7KkaG9VLJdFTn2db2l32fnvxbkTjU=,tag:UwirQVVvGrAh8nX/IASyxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaEZuSkUrWmZWeW51d0p0
            YTk3VmxpelhoblVPTndhRkJmL3ZOamNqRjFFCk1tekZZTXFMY2syZTlCVEc3VGlP
            WHlhdzJrZit3MlcvY2d4RXp6clhJUmsKLS0tIGx5YVZGRUNqblVqNHR0a3QvQ1Nl
            UzF4T2pGWGNCN2RrWlY0TFAxalQxa28KDPdTYtT5IobS6ULCyh4pw+lfo+ZU0SpI
            5QuRNQGjkNexa/kjg/Rv1mjReUB2nztkijgRgiOBSz9Y/nzii+KNMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T04:40:18Z"
    mac: ENC[AES256_GCM,data:096ljrEkoX2ftn8l4wWzbfRSW6ovS8PBBUyw1gsZ9mso0cRdXYQHivaG+Eu5Qiv8bL5WHpABDKbZgSXvcGK5khGRrkESRUaNEYD0e6CIWy22c4NCgv40PjMzF/1t66U6goUc3dr2mOokb20QtqveY1D5g1BuqQuv9kBlWTpm3Js=,iv:7EXujO1Ea4PZtmz+LzLJW53ZUMBw5WXlee9MCQrUx3g=,tag:sVpAgGV97/NzzP/Ftw+N7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.2
