# Source: deployment/templates/apps/longhorn/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: s3-store-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wYHhlW23gopAsYm1oNcqNQhQgBPp1Ro6AVZqQQ==,iv:gJjfF1USlNQbhvg02n8/oa5LellWqL39oL0se+5U2xI=,tag:ptn8qgj0MVpnT5rDVSI3rg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xzFeq7HIl06qMmNhpxataGfm1SDqcokFDAfh0L5RwwH9HQjizLkgiNwbUPNXU01NAfHqFk5KjL0=,iv:pqRRJPljUMaD956PgcejUnlz7xjJRskysvn61l/cTlY=,tag:pT6D6fdg4fi5ljmGBrOCnA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:UQclIqEgskM4CMP2pyJrsntq1Qt4HyZ5B+nJqIloJWLEfrtrtjmBKg==,iv:sky1Kf5YWUEJBfdf+KjoWVfkZVgXO1ujrwjZXabcDbE=,tag:Rm0vRjeOcoVvzFXUBU7IHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MlZFUDh0ZDR6OHEyaWlq
            RlBYOUxzTTEzY0J6bXk2NlplQ2hZOFZ4UHhJCkdNQkszZ0NuUVVtRUxVRXlVL2Z0
            Sk9tM2w5eXFaS0VYbTlsMVBWZ3NvencKLS0tIE9uclE2UlIzQWc1T3A1Z3FQYnVO
            dHlKc3doOGtrWUhZUG1NODlHcDdkUTQKvgHs6qhDN9eGHsq0NRbCXMwtgnz7YV9W
            tewJCN9GCofFPd5etdkZsub1PDNqUOmQ446P0L8kcv9QUWiDvTbEMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T05:45:15Z"
    mac: ENC[AES256_GCM,data:pmDb9G3GoOJvYfPB+k5W/HvoGnf8WEuru81WMv5rD+pqySUlRMRTZzLgyUIaYML8MxJ9s9vuH4iCRiHVDc+vlI8pfdHkO+JNCh4R9Re6n2EaXIwddkC6Y3OknbRCp8UEEu5m7EtPj3YOe4IYwNiz6ydUuYRd83gJK6EkkXgj8QA=,iv:uSTCH4xPSikRSaZi110i1ykbzqwq+UhPp0fp+O1LM0I=,tag:3kXfiNRG+pyiqXLo1OjwGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
