# Source: deployment/templates/apps/longhorn/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: s3-store-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hdDaHTZX3MyEqIe3EHfyOnYxbgoYT9nbPn1D3g==,iv:jRcb7UeyIMClvZBYNj+McswdDfJ7002pzDgEe9AOdXA=,tag:Aw2q0CkqApES2SGKkNpaBQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WF6IHi3+s8Osc2P4E9G0b+eazUfNgIyAIaj+09lQwmYmgBjelKRldVF/6/K2G+9Gb768+r4CPGQ=,iv:C02TgJX1lG389Zhup8cqUIba8QhbYFjEU0enyxTazjs=,tag:2oz5f0Yz9DQxmYI4chjuug==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:g86psaFLL4ifnhK80CXyCnaRsqzk9ndRIF38owxtuy8ANIYC/a4dJg==,iv:PbIQ8uC3puLJpA7681ijyc8RbnuekqrBjJbkJ0ibaPs=,tag:QXxrx0wzOg/uF0j1/jqYWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxfnu9czwc2hlwdjpx29ps4p5gu4tksxl40zff425vctpvpy8edqmu3ryp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmamIrY3ZENEdLbDZwcUsr
            RFhzV0pzYzZtbG1DN2NyeGlvaXhHK1F3QkVZCkhxanNvL0tWd1o2R1lVN3UvYlFD
            ZGVPVENSRWtjajg5TGpUOW1FcjlvUWsKLS0tIEtGRmtldEdNYmwvbmM1UWg3bHQw
            Umo2T0c1ZG1Cb0t3M3Rzd1ZBbENlSWMKUZauD72L0am9WPfIAJXNP62HlFwsuXLi
            SCHmYs55IJDXXE7JjNmiCdgCu185Fiwc/10dVISLEycDRiNdOmgu3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T15:50:39Z"
    mac: ENC[AES256_GCM,data:jV+bcwYqEMl8+8AdfqI/DAOX5oPrJPPPHJ866phPs4Q3BuuFyHuba+9QMpehaKJFlmglPqzXI6mJtbl0A2ZUGhAZCZKaoDKkG494gJmLvesuC/3KWZGkuEj7dX/NjX322OW2V15BwCD3xJjpF4ZNeT2lKef+uzj07hkFpovMFDo=,iv:tgPjqb6Y/rSs74OITZiL0gKVQjPilItN/BA93M9pIdA=,tag:RFD9LZVPd2zS0b90KcgFUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|acme)$
    mac_only_encrypted: true
    version: 3.9.2
