---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui-service
  namespace: longhorn-system
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: longhorn-ui
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-system-http
  namespace: longhorn-system
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: shared-default-gateway
    namespace: default
    sectionName: shared-https
  hostnames:
  - longhorn.{{ subdomain }}
  rules:
  - matches:
    - path:	
        type: PathPrefix	
        value: /
    backendRefs:
    - group: ''
      kind: Service
      name: longhorn-ui-service
      port: 8000
      weight: 1
---