kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-postgres-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "1440"
  fromBackup: ""
  fsType: "ext4"
  #diskSelector: "nvme"
  dataLocality: "strict-local"